# Generated by Django 3.2.3 on 2021-07-22 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Activity',
        ),
    ]
