# Generated by Django 3.2.3 on 2021-07-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0002_auto_20210725_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='photos',
            new_name='Photo',
        ),
    ]
