# Generated by Django 3.2.3 on 2021-07-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0003_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_center',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
