# Generated by Django 3.2.3 on 2021-07-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0004_remove_research_center_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='video',
            field=models.CharField(blank=True, help_text='<b style="color:red;font-size: 12px">*IMPORTANT* Only add either Video link or Image, If you add both, only the image will be shown</b>', max_length=1000, null=True),
        ),
    ]
