# Generated by Django 3.2.3 on 2021-07-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0006_auto_20210724_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='research_center',
            name='image_url',
        ),
    ]
