# Generated by Django 3.2.3 on 2021-07-25 12:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0007_alter_research_center_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_center',
            name='image1',
            field=cloudinary.models.CloudinaryField(help_text='<b style="color:red;font-size: 12px">*IMPORTANT* All three image should be of equal ratio (preffered: 3 x 2 )</b>', max_length=255, verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='research_center',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='research_center',
            name='image3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image3'),
        ),
        migrations.AlterField(
            model_name='research_center',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Embeded Url'),
        ),
    ]
