# Generated by Django 3.2.3 on 2021-07-24 10:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0008_auto_20210724_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_center',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
