# Generated by Django 3.2.3 on 2021-07-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0010_alter_photos_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='image',
            new_name='image_url',
        ),
    ]
