# Generated by Django 3.2.3 on 2021-07-24 11:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_centers', '0011_rename_image_photos_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='research_center',
            name='image_url',
        ),
        migrations.AddField(
            model_name='research_center',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
