# Generated by Django 3.2.3 on 2021-07-24 15:32

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Career_Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('embeded_video_link', models.TextField(blank=True, null=True)),
                ('image_url', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(null=True, to='career_talks.Category')),
            ],
            options={
                'verbose_name_plural': 'Career Talks',
            },
        ),
    ]
