# Generated by Django 3.2.4 on 2021-07-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_talks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career_talk',
            name='video_link',
        ),
        migrations.AddField(
            model_name='career_talk',
            name='embeded_video_link',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career_talk',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='career_talk',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
    ]
