# Generated by Django 3.2.4 on 2021-07-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_talks', '0002_auto_20210702_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_talk',
            name='embeded_video_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='career_talk',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
