# Generated by Django 3.2.3 on 2021-07-25 11:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_talks', '0002_alter_career_talk_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career_talk',
            name='image_url',
        ),
        migrations.AddField(
            model_name='career_talk',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
