# Generated by Django 3.2.3 on 2021-07-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_talks', '0003_auto_20210725_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_talk',
            name='embeded_video_link',
            field=models.TextField(blank=True, help_text='<b style="color:red;font-size: 12px">*IMPORTANT* Only add either Video link or Image, If you add both, only the image will be shown</b>', null=True),
        ),
    ]
