# Generated by Django 3.2.4 on 2021-07-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_talks', '0003_auto_20210702_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_Career_Talk',
        ),
        migrations.AddField(
            model_name='career_talk',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='career_talks.Category_Career_Talk'),
        ),
    ]
