# Generated by Django 3.2.4 on 2021-07-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_talks', '0004_auto_20210703_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_talk',
            name='category',
            field=models.ManyToManyField(to='career_talks.Category_Career_Talk'),
        ),
    ]
