# Generated by Django 3.2.5 on 2021-07-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_talks', '0005_alter_career_talk_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_Career_Talk',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categotries'},
        ),
    ]
