# Generated by Django 3.2.5 on 2021-07-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_talks', '0006_auto_20210703_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career_talk',
            options={'verbose_name_plural': 'Career Talks'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='career_talk',
            name='category',
            field=models.ManyToManyField(null=True, to='career_talks.Category'),
        ),
    ]
