# Generated by Django 3.2.5 on 2021-07-02 20:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_talks', '0007_auto_20210703_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career_talk',
            name='sub_text',
        ),
        migrations.AddField(
            model_name='career_talk',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
    ]
