# Generated by Django 3.2.3 on 2021-07-24 15:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200, verbose_name='Course decription')),
                ('playlist_id', models.CharField(max_length=200, verbose_name='Youtube playlist url')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image_link', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('category', models.ManyToManyField(null=True, to='courses.Category')),
            ],
        ),
    ]
