# Generated by Django 3.2.4 on 2021-06-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='choice',
            field=models.ManyToManyField(blank=True, to='courses.Choice'),
        ),
    ]
