# Generated by Django 3.2.3 on 2021-07-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image_link',
            new_name='image',
        ),
    ]
