# Generated by Django 3.2.3 on 2021-07-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_image_link_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Category'),
        ),
    ]
