# Generated by Django 3.2.3 on 2021-07-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='playlist_link',
            new_name='course_id',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
