# Generated by Django 3.2.3 on 2021-07-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210722_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='playlist_id',
        ),
    ]
