# Generated by Django 3.2.3 on 2021-07-21 20:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_course_id_course_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='files',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Provide links for resources(if any)'),
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Overview of the course'),
        ),
    ]
