# Generated by Django 3.2.3 on 2021-07-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210722_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='files',
        ),
        migrations.RemoveField(
            model_name='course',
            name='overview',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Small decription'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_link',
            field=models.CharField(max_length=200, verbose_name='Course Display Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='playlist_id',
            field=models.CharField(max_length=200, verbose_name='Youtube playlist url'),
        ),
    ]
