# Generated by Django 3.2.3 on 2021-07-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210722_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(default=None, max_length=200, verbose_name='Course decription'),
            preserve_default=False,
        ),
    ]
