# Generated by Django 3.2.3 on 2021-07-24 10:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_link',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
