# Generated by Django 3.2.5 on 2021-07-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20210703_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='title',
            new_name='name',
        ),
    ]
