# Generated by Django 3.2.5 on 2021-07-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_rename_title_contest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='info',
            field=models.TextField(null=True, verbose_name='Information of Contest'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(null=True, verbose_name='Short Description'),
        ),
    ]
