# Generated by Django 3.2.5 on 2021-07-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20210703_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Short Description'),
        ),
    ]
