# Generated by Django 3.2.5 on 2021-07-02 20:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_alter_contest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='info',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Information of Contest'),
        ),
    ]
