# Generated by Django 3.2.3 on 2021-07-20 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0009_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(null=True)),
                ('image_url', models.TextField(null=True)),
                ('video_url', models.TextField(null=True)),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
                ('likes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Submissions',
        ),
    ]
