# Generated by Django 3.2.3 on 2021-07-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_auto_20210721_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
