# Generated by Django 3.2.3 on 2021-07-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0018_book_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
