# Generated by Django 3.2.3 on 2021-07-24 10:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0021_alter_submission_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='contest',
            name='image_url',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
