# Generated by Django 3.2.3 on 2021-07-24 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0022_auto_20210724_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='caption',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contests.contest'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='image_url',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='likes',
            field=models.ManyToManyField(blank=True, editable=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
