# Generated by Django 3.2.3 on 2021-07-24 14:15

from django.db import migrations, models
import xxlimited


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0022_auto_20210724_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='image_id',
            field=models.CharField(default=xxlimited.Null, max_length=200, null=True),
        ),
    ]
