# Generated by Django 3.2.3 on 2021-07-24 13:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0025_remove_contest_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='image_url',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
