# Generated by Django 3.2.3 on 2021-07-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0026_contest_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='image_url',
            new_name='image',
        ),
    ]
